Fix the total files value
SkynetLabs/siasky-tools pull request #43
Opened 2022-08-11 09:30 UTC by ro-tex

# PULL REQUEST

## Overview

The total files value is broken because of bad number conversion.

## Example for Visual Changes

Current version:
![Screenshot 2022-08-11 at 11 26 27](https://user-images.githubusercontent.com/1464871/184104041-00609085-3aab-42fa-8409-0af00d1fa659.png)

Fixed version:
![Screenshot 2022-08-11 at 11 29 57](https://user-images.githubusercontent.com/1464871/184104456-1e0882b9-4ae2-4a5c-a9a5-0cfb5736793d.png)

## Checklist

- [ ] All git commits are signed. (REQUIRED)
- [ ] All new methods or updated methods have clear docstrings.
- [ ] Testing added or updated for new methods.
- [ ] Verified if any changes impact the WebPortal Health Checks.
- [ ] Appropriate documentation updated.
- [ ] Changelog file created.

## Issues Closed

2022-08-11 12:14 UTC, ChrisSchinnerl submitted a review, later dismissed

2022-08-11 12:41 UTC, kwypchlo requested changes

2022-08-11 12:41 UTC, kwypchlo commented on src/DataTable.js
> +    return sep === "0" ? "" : sep;
I think this will still be broken for polish locale

```
Number(1000).toLocaleString('pl-PL')
// 1000

Number(10000).toLocaleString('pl-PL')
// 10 000
```

thousands separator is a space but only after you reach at least `10 000` (`1000` does not include separator)

also if the separator would be a dot then it's a wildcard and using it in replace by regexp would remove all characters :)

I would suggest using a function to convert local string into number (also works for floats):

```js
function numberFromLocaleStr(str) {
  return Number(
    str
      .split(Number(0.1).toLocaleString()[1])
      .map((part) => part.replace(/\D/g, ""))
      .join(".")
  );
}
```

2022-08-11 12:45 UTC, kwypchlo commented on src/DataTable.js
> +    return sep === "0" ? "" : sep;
example

```js
Number(123123123.123).toLocaleString()
// '123,123,123.123'

numberFromLocaleStr('123,123,123.123')
// 123123123.123
```

2022-08-11 14:49 UTC, ro-tex commented on src/DataTable.js
> +    return sep === "0" ? "" : sep;
That's great. Changed.

2022-08-11 15:06 UTC, kwypchlo approved these changes

2022-08-12 12:51 UTC, ChrisSchinnerl approved these changes

2022-08-12 12:51 UTC, merged